// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    // Plugins automatically generated by TLGradle.kt
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.android) apply false
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
allprojects {
    tasks.withType<com.android.build.gradle.tasks.ProcessAndroidResources>().configureEach {
        doFirst {
            val aapt2Path = File("${rootDir}/aapt2").absolutePath
            val propertyName = "android.aapt2FromMavenOverride"
            System.setProperty(propertyName, aapt2Path)
            project.extensions.extraProperties.set(propertyName, aapt2Path)
        }
    }
}
